sudo: false
dist: trusty
language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on
    GOFLAGS=-mod=vendor
install:
  - make tools
script:
  - make
after_success:
  - if [[ -n "$TRAVIS_TAG" ]]; then make release; fi
notifications:
  email: true